ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'BackgroundLocationExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Call MapLibre post_install to configure SPM dependencies
    # The MapLibre podspec defines a $MLRN.post_install method that needs to be called
    # This configures the Swift Package Manager dependency for MapLibre
    begin
      maplibre_podspec_path = File.join(
        Pod::Config.instance.installation_root,
        '..',
        'node_modules',
        '@maplibre',
        'maplibre-react-native',
        'maplibre-react-native.podspec'
      )
      if File.exist?(maplibre_podspec_path)
        # Load the podspec to get access to $MLRN global object
        load maplibre_podspec_path
        # Call the post_install hook to configure SPM dependencies
        if defined?($MLRN) && $MLRN.respond_to?(:post_install)
          $MLRN.post_install(installer)
        end
      end
    rescue => e
      Pod::UI.warn "Failed to configure MapLibre: #{e.message}"
      Pod::UI.warn e.backtrace.first(5).join("\n")
    end
  end
end
